export enum Texts {
    // ЭТО МЕНЯТЬ НЕЛЬЗЯ!
    start_command = "/start",
    // Это можно менять
    start_command_response = "Привет от BEM бота. Stay BEMed",
    unknown_command_response = "Прости, я не понимаю тебя. Попробуй снова =)",
    start_online_command = "Начать онлайн викторину",
    start_offline_command = "Начать викторину на стенде",
    start_online_message = "Начинаем онлайн викторину",
    start_offline_message = "Подходи к стенду, если ты еще не на нем, и решай задачу",
    finished_quiz_message = "Ты уже прошел викторину. Приходи на стенд =)",
    return_command = "В меню",
    return_message = "Выбирай, чем хочешь заняться)",
    schedule_command = "Расписание стенда",
    schedule_message = "Держи расписание",
    switch_to_online_command = "Перейти в онлайн",
    switch_to_offline_command = "Перейти в оффлайн",
    leaderboard_command = "Leaderboard",
    leaderboard_command_response = "Ты {1} в списке лидеров. У тебя {2} правильных ответов",
    finite_mode_completed = "Ты закончил онлайн этап",
    finite_mode_not_completed = "До окончания онлайн этапа правильно ответь на {1} вопросов",
    right_answer = "Ответ правильный =)",
    wrong_answer = "Ответ неправильный =(",
    next_question_command = "Следующий вопрос",
    next_question_response = "Держи следующий вопрос",
    next_question_not_found = "Ой, кажется ты ответил на все вопросы. Аймаладец",
    add_score = "Тебе добавлены баллы: {1}. Твой текущий счет: {2}",
}